apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - namespace.yaml
  - minio.yaml
  - spark-rbac.yaml
  - spark-application.yaml
  - scheduled-spark-application.yaml
