apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: market-risk-prod
resources:
  - ../base
images:
  - name: marketrisk-api
    newName: ghcr.io/keshavbhoovaragan-cpu/marketrisk-api
    newTag: REPLACE_WITH_VERIFIED_SHA
  - name: marketrisk-frontend
    newName: ghcr.io/keshavbhoovaragan-cpu/marketrisk-frontend
    newTag: REPLACE_WITH_VERIFIED_SHA
patches:
  - path: deployment-settings.yaml
